### ISSUE TITLE
Milestone 3 tasks

### ISSUE THREAD

**Issue by jchen9314** [UBC-MDS/prepackR#20]
- [x] address feedback from TA 
- [x] write functions for the R package
- [x] pass all test cases and reach 100% test coverage
- [x] select a license for the R package
- [x] use devtools::install_github("PACKAGE_NAME") for R package
- [x] update package README (including usage and installation instructions, a screenshot of test coverage report)
- [x] use GitHub's issue tracker and milestone feature to plan the milestone. (document tasks in issues and assign each issue to Milestone 3)

**Comment by apchiodo** [comment]
We are in good shape!
