### ISSUE TITLE
Milestone 4 (Final project) tasks

### ISSUE THREAD

**Issue by jchen9314** [UBC-MDS/prepackR#29]
- [x] Address feedback from TA.
- [x] Add appropriate exception handler (both in Python and in R package code) for all functions.
- [x] Add adequate integration tests in each package, if applicable.
- [x] Set up continuous integration testing using Travis and add a passing build stamp for each package README files.
- [x] In your README, include a clear description of how to install your package and call your functions. Also, include an example with a toy dataset and a screenshot of the output when you run tests.
